# Generated by Django 5.1 on 2024-10-19 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2024, 10, 19, 15, 10, 37, 555636, tzinfo=datetime.timezone.utc)),
        ),
    ]
